/**
 * Error Codes
 * Centralized error code constants
 */
export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  REFERENCE_ERROR: "REFERENCE_ERROR",
  TYPE_ERROR: "TYPE_ERROR",
  SYNTAX_ERROR: "SYNTAX_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  CLIENT_ERROR: "CLIENT_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;
